# Generated by Django 4.2.16 on 2024-10-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohlcvdata',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datum', to='market.exchange'),
            preserve_default=False,
        ),
    ]
