# Generated by Django 4.2.16 on 2024-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_ohlcvdata_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohlcvdata',
            name='is_pump',
            field=models.BooleanField(default=False, help_text='This boolean value is set by the'),
        ),
        migrations.AddField(
            model_name='ohlcvdata',
            name='is_pump_non_ml',
            field=models.BooleanField(default=False, help_text='This boolean value will either be set manually or programatically'),
        ),
    ]
