# Generated by Django 4.2.16 on 2024-10-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnds', '0003_scheduledpump_message'),
        ('market', '0003_ohlcvdata_is_pump_ohlcvdata_is_pump_non_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohlcvdata',
            name='pnd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='pnds.scheduledpump'),
        ),
    ]
