# Generated by Django 4.2.16 on 2024-10-25 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_ohlcvdata_pnd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohlcvdata',
            name='pnd',
        ),
        migrations.AddField(
            model_name='ohlcvdata',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ohlcvdata',
            name='is_pump',
            field=models.BooleanField(default=False, help_text='This boolean value is set by the classifier '),
        ),
    ]
