# Generated by Django 4.2.16 on 2024-12-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_ohlcvdata_pnd_ohlcvdata_received_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ohlcvdata',
            unique_together={('exchange', 'coin', 'pair', 'market_time')},
        ),
    ]
