# Generated by Django 4.2.16 on 2024-12-08 17:21

from django.db import migrations
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_ohlcvdata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohlcvdata',
            name='interval',
            field=market.models.IntervalField(choices=[('1m', '1-minute')], default='1m', max_length=5),
        ),
    ]
