# Generated by Django 4.2.16 on 2024-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_ohlcvdata_is_pump_non_ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlcvdata',
            name='is_pump_non_ml',
            field=models.BooleanField(blank=True, help_text='This boolean value will either be set manually or programatically', null=True),
        ),
    ]
