# Generated by Django 4.2.16 on 2024-10-01 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('false_alarm', models.BooleanField(default=False)),
                ('pair_guessed', models.BooleanField(default=False)),
                ('manually_corrected', models.BooleanField(default=False)),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pump_pair', to='market.coin')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pump_target', to='market.coin')),
            ],
        ),
    ]
