# Generated by Django 4.2.16 on 2024-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_ohlcvdata_pnd_ohlcvdata_received_at_and_more'),
        ('pnds', '0003_scheduledpump_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledpump',
            name='exchange',
        ),
        migrations.AddField(
            model_name='scheduledpump',
            name='exchanges',
            field=models.ManyToManyField(related_name='schduled', to='market.exchange'),
        ),
    ]
