# Generated by Django 4.2.16 on 2024-12-08 17:25

from django.db import migrations
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('pnds', '0004_remove_scheduledpump_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpump',
            name='interval',
            field=market.models.IntervalField(choices=[('1m', '1-minute')], default='1m', max_length=5),
        ),
    ]
