# Generated by Django 4.2.16 on 2024-12-08 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_alter_message_content_type'),
        ('pnds', '0005_scheduledpump_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpump',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forums.message'),
        ),
    ]
